name: Deploy


on:
  release:
        types: [ "published" ]



jobs:
    deploy:
        runs-on: [self-hosted]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: install tools
              run: python3 -m pip install --user --upgrade twine build

            - name: build
              run: python3 -m build

            # - name: publish
            # - run: >
            #     python3 -m twine upload
            #     --repository-url ${{ secrets.PYPI_URL }}
            #     --username ${{ secrets.PYPI_USERNAME }}
            #     --password ${{ secrets.PYPI_PASSWORD }}
            #     --skip-existing
            #     dist/*
